"""add_dashboard_tables

Revision ID: 7b6d2c52870b
Revises: 7792d87c1d07
Create Date: 2026-06-14 13:44:43.461794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6d2c52870b'
down_revision: Union[str, Sequence[str], None] = '7792d87c1d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # --- Fix machines table FIRST (before anything references machines.id) ---
    op.drop_index(op.f('ix_machines_mc_id'), table_name='machines')
    op.drop_column('machines', 'mc_id')
    op.add_column('machines', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.execute('ALTER TABLE machines ADD PRIMARY KEY (id)')
    op.add_column('machines', sa.Column('machine_type', sa.String(length=100), nullable=True))
    op.add_column('machines', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('machines', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('machines', 'plant_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # --- Now create tables that reference machines.id ---
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)

    op.create_table('productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('units_produced', sa.Integer(), nullable=True),
    sa.Column('target_units', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productions_id'), 'productions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('mc_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.create_index(op.f('ix_machines_mc_id'), 'machines', ['mc_id'], unique=False)
    op.alter_column('machines', 'plant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('machines', 'created_at')
    op.drop_column('machines', 'status')
    op.drop_column('machines', 'machine_type')
    op.drop_column('machines', 'id')
    op.drop_index(op.f('ix_productions_id'), table_name='productions')
    op.drop_table('productions')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
