"""add_simulation_columns_to_productions

Revision ID: d6931fcc7b0d
Revises: 145551eff527
Create Date: 2026-06-24 00:21:12.571832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6931fcc7b0d'
down_revision: Union[str, Sequence[str], None] = '145551eff527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productions', sa.Column('defect_qty', sa.Integer(), nullable=True))
    op.add_column('productions', sa.Column('oee_score', sa.Float(), nullable=True))
    op.add_column('productions', sa.Column('defect_type', sa.String(length=100), nullable=True))
    op.alter_column('productions', 'rejected_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productions', 'rejected_qty',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('productions', 'defect_type')
    op.drop_column('productions', 'oee_score')
    op.drop_column('productions', 'defect_qty')
    # ### end Alembic commands ###
